# Generated by Django 5.2.4 on 2025-07-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('current_mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('excited', 'Excited'), ('stressed', 'Stressed'), ('neutral', 'Neutral')])),
            ],
        ),
    ]
